version: "3"
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
          - '8080:80'
        volumes:
          . D:\ict\DevOps\jenkins-demo:/usr/local/nginx
        restart: always
            
            
             
            