apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx-deployment
  labels:
    app: mysite
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysite
  spec:
    containers:
    -name: my-static-site-container
    image: nginx
    volumeMounts:
      - name: site-content
        mountPath: /usr/share/nginx/html
    volumes:
      -name: site-content
      hostPath: /home/kali/site
    ports:
    - containerPort: 8080