---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: t0b9.mysite.com
      http:
        paths:
        - backend:
            service:
              name: site-service
              port:
                number: 8080
          path: /
          pathType: Prefix